### ISSUE TITLE
Experiment # 1: Measure log likelihood for CNF against one-way tensor (vector) GMM with different dimensions (Expressive power work) 

### ISSUE THREAD

**Issue by mbaddar1** [mbaddar1/phd#10]
https://github.com/mbaddar1/phd/blob/experiments1/cnf/examples/cnf_gmm.py

**Comment by mbaddar1** [comment]
FIx the problem for 2D GMM
====
/home/mohamed1/Documents/mbaddar/phd2/repo/venv3/bin/python3 /home/mohamed1/Documents/mbaddar/phd2/phd/cnf/examples/cnf_gmm.py
/home/mohamed1/Documents/mbaddar/phd2/repo/venv3/lib/python3.8/site-packages/torch/distributions/distribution.py:161: UserWarning: sample_n will be deprecated. Use .sample((n,)) instead
  warnings.warn('sample_n will be deprecated. Use .sample((n,)) instead', UserWarning)
INFO:cnf_fit:Starting CNF fit
  0%|          | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/mohamed1/Documents/mbaddar/phd2/phd/cnf/examples/cnf_gmm.py", line 108, in <module>
    cnf_func_fit = cnf_fit(base_dist=base_dist, target_dist=target_dist, t0=t0, t1=t1, in_out_dim=X_dim,
  File "/home/mohamed1/Documents/mbaddar/phd2/phd/cnf/examples/cnf_gmm.py", line 52, in cnf_fit
    loss.backward()
  File "/home/mohamed1/Documents/mbaddar/phd2/repo/venv3/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/mohamed1/Documents/mbaddar/phd2/repo/venv3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 150, in backward
    grad_tensors_ = _make_grads(tensors, grad_tensors_)
  File "/home/mohamed1/Documents/mbaddar/phd2/repo/venv3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 51, in _make_grads
    raise RuntimeError("grad can be implicitly created only for scalar outputs")
RuntimeError: grad can be implicitly created only for scalar outputs

Process finished with exit code 1

====

**Comment by mbaddar1** [comment]
Artifacts
https://www.overleaf.com/project/61e32db4e84fdd83c387ec77
sec 5.1
https://github.com/mbaddar1/phd/blob/master/cnf/examples/cnf_gmm.py
